INPUT:
  SIZE: (17, 384)
  TRANSFORMS: []
  NO_TRANSFORM: True

USE_CUDA: True


DATAMANAGER:
  RESULT_FOLDER: 'result_folder'
  MANAGER_TYPE: 'single_dataset'
  DATASET:
    NAME: 'MultiDataset'
    DIR: 'case_16_B'
    FILENAME: 'NeurIPS_TL.mat'
    extra_files: [ 'LA/dataset_1.mat','LA/dataset_2.mat','LA/dataset_3.mat']
    r_op_file: 'dataset_B_r_op.mat'
#    target_dataset_relabelled: True
    USE_Euclidean_Aligment: True
    source_dataset_LA: True
    SETUP:
      TARGET_DATASET_NAME: 'dataset_B'
      SOURCE_DATASET_NAMES: [ ]
      TEST_FOLD:
        N_TEST_FOLDS: 1
        TEST_FOLD_PREFIX: 'test_fold'
        START_TEST_FOLD: 1
        END_TEST_FOLD: 1
        CURRENT_TEST_FOLD: 1
        WITHIN_SUBJECTS: True
        TRAIN_VALID_DATA_RATIO: -1
        SAME_AS_VALID: True
      SHUFFLE_TRAIN_VALID_FOLD:
        SHUFFLE_FOLD_PREFIX: 'shuffle_fold'
        N_SHUFFLE_FOLDS: 1
        START_SHUFFLE_FOLD: 1
        END_SHUFFLE_FOLD: 1
        CURRENT_SHUFFLE_FOLD: 1
        SHUFFLE_SEED: []
      INCREMENT_FOLD:
        INCREMENT_FOLD_PREFIX: 'increment_fold'
        N_INCREMENT_FOLDS: 1
        START_NUM_TRAIN_SUGJECT: 3
        INCREMENT_TRAIN_SUGJECT: 0
        START_INCREMENT_FOLD: 1
        END_INCREMENT_FOLD: 1
        CURRENT_INCREMENT_FOLD: 1
      VALID_FOLD:
        VALID_FOLD_PREFIX: 'valid_fold'
        N_VALID_FOLDS: 5
        START_VALID_FOLD: 1
        END_VALID_FOLD: 5
        CURRENT_VALID_FOLD: 1
        WITHIN_SUBJECTS: True
        TRAIN_DATA_RATIO: -1
        TOTAL_CLASS_WEIGHT: True
    AUGMENTATION:
      NAME: ""
      PARAMS:
        N_SEGMENT: 4
        MAX_TRIAL_MUL: 3
        MAX_FIX_TRIAL: -1
        DATASET_NAME: "BCI_IV"
  DATALOADER:
    NUM_WORKERS: 0
    TRAIN_X:
      SAMPLER: RandomSampler
      BATCH_SIZE: 32
    VALID:
      SAMPLER: SequentialSampler
      BATCH_SIZE: 64
    TEST:
      SAMPLER: SequentialSampler
      BATCH_SIZE: 64

OPTIM:
  OPTIMIZER:
    NAME: adam
    PARAMS:
      lr: 0.001
      weight_decay: 0.0
  SCHEDULER:
    NAME: exponential
    PARAMS:
      gamma: 1.0
  MAX_EPOCH: 60

TRAIN:
  CHECKPOINT_FREQ: 0
  PRINT_FREQ: 10


TEST:
  EVALUATOR: 'Classification'
  PER_CLASS_RESULT: True

LIGHTNING_MODEL:
  TRAINER:
    NAME: 'BaseModel'
  COMPONENTS:
    LAST_FC:
      NAME: max_norm
      max_norm: 0.5
    BACKBONE:
      NAME: 'eegnet'
      PARAMS:
        kern_legnth: 64
        num_ch: 17
        samples: 384
        F1: 8
        D: 2
        F2: 16
        drop_prob: 0.25
        avg_pool_1: 4
        avg_pool_2: 8
        sep_kern_length: 16



EXTRA_FIELDS:
  target_dataset: 'dataset_B'
  source_dataset: []
  normalize: 'no_norm'
  EA: True
  LA: True
  aug: 'no_aug'
  model: 'BaseModel'
  backbone: 'eegnet'
  source_label_space: []
  target_label_space: 4
