INPUT:
  SIZE: (31, 384)
  TRANSFORMS: []
  NO_TRANSFORM: true
USE_CUDA: true
DATAMANAGER:
  RESULT_FOLDER: result_folder
  MANAGER_TYPE: multi_dataset
  DATASET:
    NAME: MultiDataset
    DIR: case_5_B
    FILENAME: NeurIPS_TL.mat
    SETUP:
      TARGET_DATASET_NAME: dataset_B
      TEST_FOLD:
        N_TEST_FOLDS: 5
        TEST_FOLD_PREFIX: test_fold
        START_TEST_FOLD: 1
        END_TEST_FOLD: 5
        CURRENT_TEST_FOLD: 1
        WITHIN_SUBJECTS: true
        TRAIN_VALID_DATA_RATIO: -1
      SHUFFLE_TRAIN_VALID_FOLD:
        SHUFFLE_FOLD_PREFIX: shuffle_fold
        N_SHUFFLE_FOLDS: 1
        START_SHUFFLE_FOLD: 1
        END_SHUFFLE_FOLD: 1
        CURRENT_SHUFFLE_FOLD: 1
        SHUFFLE_SEED: []
      INCREMENT_FOLD:
        INCREMENT_FOLD_PREFIX: increment_fold
        N_INCREMENT_FOLDS: 1
        START_NUM_TRAIN_SUGJECT: 3
        INCREMENT_TRAIN_SUGJECT: 0
        START_INCREMENT_FOLD: 1
        END_INCREMENT_FOLD: 1
        CURRENT_INCREMENT_FOLD: 1
      VALID_FOLD:
        VALID_FOLD_PREFIX: valid_fold
        N_VALID_FOLDS: 4
        START_VALID_FOLD: 1
        END_VALID_FOLD: 4
        CURRENT_VALID_FOLD: 1
        WITHIN_SUBJECTS: true
        TRAIN_DATA_RATIO: -1
        TOTAL_CLASS_WEIGHT: true
    AUGMENTATION:
      NAME: temporal_segment
      PARAMS:
        N_SEGMENT: 4
        MAX_TRIAL_MUL: 3
        MAX_FIX_TRIAL: -1
        DATASET_NAME: BCI_IV
    FILTERBANK:
      USE_FILTERBANK: true
      freq_interval: 4
  DATALOADER:
    NUM_WORKERS: 0
    TRAIN_X:
      SAMPLER: RandomSampler
      BATCH_SIZE: 64
    LIST_TRAIN_U:
      SAMPLERS:
        - RandomSampler
        - RandomSampler
        - RandomSampler
      BATCH_SIZES:
        - 64
        - 64
        - 64
    VALID:
      SAMPLER: SequentialSampler
      BATCH_SIZE: 64
    TEST:
      SAMPLER: SequentialSampler
      BATCH_SIZE: 64
OPTIM:
  OPTIMIZER:
    NAME: adam
    PARAMS:
      lr: 0.001
      weight_decay: 0.0
  SCHEDULER:
    NAME: exponential
    PARAMS:
      gamma: 1.0
  MAX_EPOCH: 20
TRAIN:
  CHECKPOINT_FREQ: 0
  PRINT_FREQ: 10
TEST:
  EVALUATOR: Classification
  PER_CLASS_RESULT: true
LIGHTNING_MODEL:
  TRAINER:
    NAME: MultiDatasetAdaptationV1
    EXTRA:
      TARGET_LOSS_RATIO: 0.8
      SOURCE_LOSS_RATIO: 0.2
      SOURCE_PRE_TRAIN_EPOCHS: 10
  COMPONENTS:
    LAST_FC:
      NAME: max_norm
      max_norm: 0.5
    BACKBONE:
      NAME: fbcnet
      PARAMS:
        nChan: 31
        nBands: 8
        m: 32
        temporalLayer: LogVarLayer
        strideFactor: 6
EXTRA_FIELDS:
  target_dataset: dataset_B
  source_dataset:
    - cho2017
    - physionet
    - BCI_IV
  normalize: no_norm
  aug: temporal_aug
  model: MultiDatasetAdaptationV1
  backbone: fbcnet
  source_label_space:
    - 2
    - 3
    - 3
  target_label_space: 3
