INPUT:
  SIZE: (22, 384)
  TRANSFORMS: []
  NO_TRANSFORM: true
USE_CUDA: true
DATAMANAGER:
  RESULT_FOLDER: result_folder
  MANAGER_TYPE: single_dataset
  DATASET:
    NAME: MultiDataset
    DIR: private_data_16
    FILENAME: train_data_TL.mat
    extra_files:
      - dataset_1.mat
      - dataset_2.mat
    TEST_DIR: private_data_16
    TEST_DATA_FILE: test_data_TL.mat
    r_op_file: dataset_r_op.mat
    TEST_SET_FILENAME: test_data_TL.mat
    USE_Euclidean_Aligment: true
    SETUP:
      TARGET_DATASET_NAME: BCI_IV
      SOURCE_DATASET_NAMES: []
      TEST_FOLD:
        N_TEST_FOLDS: 1
        TEST_FOLD_PREFIX: test_fold
        START_TEST_FOLD: 1
        END_TEST_FOLD: 1
        CURRENT_TEST_FOLD: 1
        WITHIN_SUBJECTS: true
        TRAIN_VALID_DATA_RATIO: -1
      SHUFFLE_TRAIN_VALID_FOLD:
        SHUFFLE_FOLD_PREFIX: shuffle_fold
        N_SHUFFLE_FOLDS: 1
        START_SHUFFLE_FOLD: 1
        END_SHUFFLE_FOLD: 1
        CURRENT_SHUFFLE_FOLD: 1
        SHUFFLE_SEED: []
      INCREMENT_FOLD:
        INCREMENT_FOLD_PREFIX: increment_fold
        N_INCREMENT_FOLDS: 1
        START_NUM_TRAIN_SUGJECT: 9
        INCREMENT_TRAIN_SUGJECT: 0
        START_INCREMENT_FOLD: 1
        END_INCREMENT_FOLD: 1
        CURRENT_INCREMENT_FOLD: 1
      VALID_FOLD:
        VALID_FOLD_PREFIX: valid_fold
        N_VALID_FOLDS: 4
        START_VALID_FOLD: 1
        END_VALID_FOLD: 4
        CURRENT_VALID_FOLD: 1
        WITHIN_SUBJECTS: true
        TRAIN_DATA_RATIO: -1
        TOTAL_CLASS_WEIGHT: true
    AUGMENTATION:
      NAME: temporal_segment
      PARAMS:
        N_SEGMENT: 4
        MAX_TRIAL_MUL: 3
        MAX_FIX_TRIAL: -1
        DATASET_NAME: BCI_IV
  DATALOADER:
    NUM_WORKERS: 0
    TRAIN_X:
      SAMPLER: RandomSampler
      BATCH_SIZE: 32
    TRAIN_U:
      SAMPLER: RandomSampler
      BATCH_SIZE: 32
    LIST_TRAIN_U:
      SAMPLERS:
        - RandomSampler
        - RandomSampler
      BATCH_SIZES:
        - 32
        - 32
    VALID:
      SAMPLER: SequentialSampler
      BATCH_SIZE: 64
    TEST:
      SAMPLER: SequentialSampler
      BATCH_SIZE: 64
OPTIM:
  OPTIMIZER:
    NAME: adam
    PARAMS:
      lr: 0.001
      weight_decay: 0.0
  SCHEDULER:
    NAME: exponential
    PARAMS:
      gamma: 1.0
  MAX_EPOCH: 35
TRAIN:
  CHECKPOINT_FREQ: 0
  PRINT_FREQ: 10
TEST:
  EVALUATOR: Classification
  PER_CLASS_RESULT: true
LIGHTNING_MODEL:
  TRAINER:
    NAME: BaseModel
  COMPONENTS:
    LAST_FC:
      NAME: max_norm
      max_norm: 0.5
    BACKBONE:
      NAME: eegnet
      PARAMS:
        kern_legnth: 64
        num_ch: 22
        samples: 384
        F1: 8
        D: 2
        F2: 16
        drop_prob: 0.25
        avg_pool_1: 4
        avg_pool_2: 8
        sep_kern_length: 16
EXTRA_FIELDS:
  target_dataset: BCI_IV
  source_dataset:
    - cho2017
    - physionet
  normalize: no_norm
  EA: true
  LA: false
  aug: temporal_aug
  model: BaseModel
  backbone: eegnet
  source_label_space:
    - 2
    - 4
    - 4
  target_label_space: 4
